import type { BaseProfile } from '../../types';
import { realProfiles } from './realProfiles';

// Demo profiles as fallback (keeping original demo profiles for reference)
const demoProfiles: BaseProfile[] = [
    {
        id: 'mk4-04-quality',
        name: 'MK4 0.4mm Quality',
        description: 'High quality profile for MK4 with 0.4mm nozzle',
        version: '1.0',
        metadata: {
            printer: 'Prusa MK4',
            nozzle: '0.4mm',
            material: 'PLA',
            quality: 'High',
            author: 'Prusa Research',
            created: '2024-01-01',
        },
        data: {
            print_settings: {
                layer_height: 0.2,
                first_layer_height: 0.2,
                perimeter_speed: 45,
                infill_speed: 80,
                travel_speed: 150,
                fill_density: 20,
                fill_pattern: 'grid',
                perimeters: 2,
                top_solid_layers: 4,
                bottom_solid_layers: 3,
                skirts: 1,
                skirt_distance: 6,
                support_material: false,
                support_material_threshold: 0,
                brim_width: 0,
                fuzzy_skin: 'none',
                fuzzy_skin_thickness: 0.3,
                fuzzy_skin_point_dist: 0.8,
                external_perimeter_speed: 25,
            },
            filament_settings: {
                temperature: 215,
                first_layer_temperature: 215,
                bed_temperature: 60,
                first_layer_bed_temperature: 60,
                fan_always_on: true,
                min_fan_speed: 35,
                max_fan_speed: 100,
                bridge_fan_speed: 100,
                disable_fan_first_layers: 3,
                filament_diameter: 1.75,
                extrusion_multiplier: 1.0,
            },
            printer_settings: {
                bed_size_x: 250,
                bed_size_y: 210,
                max_layer_height: 0.25,
                min_layer_height: 0.05,
                nozzle_diameter: 0.4,
                retract_length: 3.2,
                retract_speed: 70,
                travel_speed: 150,
            },
        },
    },
    {
        id: 'mk4-04-speed',
        name: 'MK4 0.4mm Speed',
        description: 'Fast printing profile for MK4 with 0.4mm nozzle',
        version: '1.0',
        metadata: {
            printer: 'Prusa MK4',
            nozzle: '0.4mm',
            material: 'PLA',
            quality: 'Medium',
            author: 'Prusa Research',
            created: '2024-01-01',
        },
        data: {
            print_settings: {
                layer_height: 0.3,
                first_layer_height: 0.2,
                perimeter_speed: 60,
                infill_speed: 100,
                travel_speed: 180,
                fill_density: 15,
                fill_pattern: 'grid',
                perimeters: 2,
                top_solid_layers: 3,
                bottom_solid_layers: 3,
                skirts: 1,
                skirt_distance: 6,
                support_material: false,
                support_material_threshold: 0,
                brim_width: 0,
                fuzzy_skin: 'none',
                fuzzy_skin_thickness: 0.3,
                fuzzy_skin_point_dist: 0.8,
                external_perimeter_speed: 25,
            },
            filament_settings: {
                temperature: 220,
                first_layer_temperature: 215,
                bed_temperature: 60,
                first_layer_bed_temperature: 60,
                fan_always_on: true,
                min_fan_speed: 30,
                max_fan_speed: 100,
                bridge_fan_speed: 100,
                disable_fan_first_layers: 3,
                filament_diameter: 1.75,
                extrusion_multiplier: 1.0,
            },
            printer_settings: {
                bed_size_x: 250,
                bed_size_y: 210,
                max_layer_height: 0.35,
                min_layer_height: 0.05,
                nozzle_diameter: 0.4,
                retract_length: 3.2,
                retract_speed: 70,
                travel_speed: 180,
            },
        },
    },
    {
        id: 'mk4-06-draft',
        name: 'MK4 0.6mm Draft',
        description: 'Very fast draft profile for MK4 with 0.6mm nozzle',
        version: '1.0',
        metadata: {
            printer: 'Prusa MK4',
            nozzle: '0.6mm',
            material: 'PLA',
            quality: 'Draft',
            author: 'Prusa Research',
            created: '2024-01-01',
        },
        data: {
            print_settings: {
                layer_height: 0.4,
                first_layer_height: 0.3,
                perimeter_speed: 80,
                infill_speed: 120,
                travel_speed: 200,
                fill_density: 10,
                fill_pattern: 'grid',
                perimeters: 2,
                top_solid_layers: 3,
                bottom_solid_layers: 2,
                skirts: 1,
                skirt_distance: 6,
                support_material: false,
                support_material_threshold: 0,
                brim_width: 0,
                fuzzy_skin: 'none',
                fuzzy_skin_thickness: 0.3,
                fuzzy_skin_point_dist: 0.8,
                external_perimeter_speed: 25,
            },
            filament_settings: {
                temperature: 225,
                first_layer_temperature: 220,
                bed_temperature: 60,
                first_layer_bed_temperature: 60,
                fan_always_on: true,
                min_fan_speed: 25,
                max_fan_speed: 100,
                bridge_fan_speed: 100,
                disable_fan_first_layers: 2,
                filament_diameter: 1.75,
                extrusion_multiplier: 1.0,
            },
            printer_settings: {
                bed_size_x: 250,
                bed_size_y: 210,
                max_layer_height: 0.5,
                min_layer_height: 0.1,
                nozzle_diameter: 0.6,
                retract_length: 3.2,
                retract_speed: 70,
                travel_speed: 200,
            },
        },
    },
];

// Use real profiles if available, otherwise fall back to demo profiles
export const baseProfiles: BaseProfile[] = realProfiles.length > 0 ? realProfiles : demoProfiles; 