name: E2E Tests (Manual)

on:
  # Only run manually for now - uncomment push/pull_request when tests are ready
  workflow_dispatch:
  # push:
  #   branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install chromium
      
    - name: Build application
      run: npm run build
      
    - name: Start preview server
      run: |
        npm run preview &
        echo $! > preview.pid
        sleep 10 # Wait for server to start
        
    - name: Check server is running
      run: |
        curl -f http://localhost:4173 || exit 1
        
    - name: Run E2E tests
      env:
        CI: true
        BASE_URL: http://localhost:4173
      run: npm run test:e2e
      
    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-node-${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 7
        
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-node-${{ matrix.node-version }}
        path: test-results/
        retention-days: 7
        
    - name: Stop preview server
      if: always()
      run: |
        if [ -f preview.pid ]; then
          kill $(cat preview.pid) || true
          rm preview.pid
        fi

  # Separate performance test job (also manual for now)
  performance-tests:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: false  # Disabled for now
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install chromium
      
    - name: Build application
      run: npm run build
      
    - name: Start preview server
      run: |
        npm run preview &
        echo $! > preview.pid
        sleep 10
        
    - name: Run performance tests
      env:
        CI: true
        BASE_URL: http://localhost:4173
      run: npx playwright test tests/e2e/performance.test.ts
      
    - name: Upload performance artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: performance-report
        path: playwright-report/
        retention-days: 7
        
    - name: Stop preview server
      if: always()
      run: |
        if [ -f preview.pid ]; then
          kill $(cat preview.pid) || true
          rm preview.pid
        fi 